// Generated by gencpp from file humandetection/abort_activity.msg
// DO NOT EDIT!


#ifndef HUMANDETECTION_MESSAGE_ABORT_ACTIVITY_H
#define HUMANDETECTION_MESSAGE_ABORT_ACTIVITY_H

#include <ros/service_traits.h>


#include <humandetection/abort_activityRequest.h>
#include <humandetection/abort_activityResponse.h>


namespace humandetection
{

struct abort_activity
{

typedef abort_activityRequest Request;
typedef abort_activityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct abort_activity
} // namespace humandetection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::humandetection::abort_activity > {
  static const char* value()
  {
    return "f1ec71d84e024b77cbdc293016ea6480";
  }

  static const char* value(const ::humandetection::abort_activity&) { return value(); }
};

template<>
struct DataType< ::humandetection::abort_activity > {
  static const char* value()
  {
    return "humandetection/abort_activity";
  }

  static const char* value(const ::humandetection::abort_activity&) { return value(); }
};


// service_traits::MD5Sum< ::humandetection::abort_activityRequest> should match 
// service_traits::MD5Sum< ::humandetection::abort_activity > 
template<>
struct MD5Sum< ::humandetection::abort_activityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::humandetection::abort_activity >::value();
  }
  static const char* value(const ::humandetection::abort_activityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::humandetection::abort_activityRequest> should match 
// service_traits::DataType< ::humandetection::abort_activity > 
template<>
struct DataType< ::humandetection::abort_activityRequest>
{
  static const char* value()
  {
    return DataType< ::humandetection::abort_activity >::value();
  }
  static const char* value(const ::humandetection::abort_activityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::humandetection::abort_activityResponse> should match 
// service_traits::MD5Sum< ::humandetection::abort_activity > 
template<>
struct MD5Sum< ::humandetection::abort_activityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::humandetection::abort_activity >::value();
  }
  static const char* value(const ::humandetection::abort_activityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::humandetection::abort_activityResponse> should match 
// service_traits::DataType< ::humandetection::abort_activity > 
template<>
struct DataType< ::humandetection::abort_activityResponse>
{
  static const char* value()
  {
    return DataType< ::humandetection::abort_activity >::value();
  }
  static const char* value(const ::humandetection::abort_activityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HUMANDETECTION_MESSAGE_ABORT_ACTIVITY_H
