// Generated by gencpp from file humandetection/ChangeClassifierGoal.msg
// DO NOT EDIT!


#ifndef HUMANDETECTION_MESSAGE_CHANGECLASSIFIERGOAL_H
#define HUMANDETECTION_MESSAGE_CHANGECLASSIFIERGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace humandetection
{
template <class ContainerAllocator>
struct ChangeClassifierGoal_
{
  typedef ChangeClassifierGoal_<ContainerAllocator> Type;

  ChangeClassifierGoal_()
    : classifier(0)  {
    }
  ChangeClassifierGoal_(const ContainerAllocator& _alloc)
    : classifier(0)  {
  (void)_alloc;
    }



   typedef uint16_t _classifier_type;
  _classifier_type classifier;




  typedef boost::shared_ptr< ::humandetection::ChangeClassifierGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::humandetection::ChangeClassifierGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeClassifierGoal_

typedef ::humandetection::ChangeClassifierGoal_<std::allocator<void> > ChangeClassifierGoal;

typedef boost::shared_ptr< ::humandetection::ChangeClassifierGoal > ChangeClassifierGoalPtr;
typedef boost::shared_ptr< ::humandetection::ChangeClassifierGoal const> ChangeClassifierGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::humandetection::ChangeClassifierGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::humandetection::ChangeClassifierGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace humandetection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/msg', '/opt/ros/indigo/share/sensor_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/msg'], 'humandetection': ['humandetection/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::humandetection::ChangeClassifierGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::humandetection::ChangeClassifierGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::humandetection::ChangeClassifierGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::humandetection::ChangeClassifierGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::humandetection::ChangeClassifierGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::humandetection::ChangeClassifierGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::humandetection::ChangeClassifierGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a407d36825e6bb6b8eccbb004fe29bac";
  }

  static const char* value(const ::humandetection::ChangeClassifierGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa407d36825e6bb6bULL;
  static const uint64_t static_value2 = 0x8eccbb004fe29bacULL;
};

template<class ContainerAllocator>
struct DataType< ::humandetection::ChangeClassifierGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "humandetection/ChangeClassifierGoal";
  }

  static const char* value(const ::humandetection::ChangeClassifierGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::humandetection::ChangeClassifierGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# service ChangeClassifier\n\
uint16 classifier\n\
";
  }

  static const char* value(const ::humandetection::ChangeClassifierGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::humandetection::ChangeClassifierGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.classifier);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ChangeClassifierGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::humandetection::ChangeClassifierGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::humandetection::ChangeClassifierGoal_<ContainerAllocator>& v)
  {
    s << indent << "classifier: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.classifier);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMANDETECTION_MESSAGE_CHANGECLASSIFIERGOAL_H
