// Generated by gencpp from file humandetection/connect_port.msg
// DO NOT EDIT!


#ifndef HUMANDETECTION_MESSAGE_CONNECT_PORT_H
#define HUMANDETECTION_MESSAGE_CONNECT_PORT_H

#include <ros/service_traits.h>


#include <humandetection/connect_portRequest.h>
#include <humandetection/connect_portResponse.h>


namespace humandetection
{

struct connect_port
{

typedef connect_portRequest Request;
typedef connect_portResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct connect_port
} // namespace humandetection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::humandetection::connect_port > {
  static const char* value()
  {
    return "f373a4b174400403f47052cfc240215e";
  }

  static const char* value(const ::humandetection::connect_port&) { return value(); }
};

template<>
struct DataType< ::humandetection::connect_port > {
  static const char* value()
  {
    return "humandetection/connect_port";
  }

  static const char* value(const ::humandetection::connect_port&) { return value(); }
};


// service_traits::MD5Sum< ::humandetection::connect_portRequest> should match 
// service_traits::MD5Sum< ::humandetection::connect_port > 
template<>
struct MD5Sum< ::humandetection::connect_portRequest>
{
  static const char* value()
  {
    return MD5Sum< ::humandetection::connect_port >::value();
  }
  static const char* value(const ::humandetection::connect_portRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::humandetection::connect_portRequest> should match 
// service_traits::DataType< ::humandetection::connect_port > 
template<>
struct DataType< ::humandetection::connect_portRequest>
{
  static const char* value()
  {
    return DataType< ::humandetection::connect_port >::value();
  }
  static const char* value(const ::humandetection::connect_portRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::humandetection::connect_portResponse> should match 
// service_traits::MD5Sum< ::humandetection::connect_port > 
template<>
struct MD5Sum< ::humandetection::connect_portResponse>
{
  static const char* value()
  {
    return MD5Sum< ::humandetection::connect_port >::value();
  }
  static const char* value(const ::humandetection::connect_portResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::humandetection::connect_portResponse> should match 
// service_traits::DataType< ::humandetection::connect_port > 
template<>
struct DataType< ::humandetection::connect_portResponse>
{
  static const char* value()
  {
    return DataType< ::humandetection::connect_port >::value();
  }
  static const char* value(const ::humandetection::connect_portResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HUMANDETECTION_MESSAGE_CONNECT_PORT_H
