// Generated by gencpp from file humandetection/connect_service.msg
// DO NOT EDIT!


#ifndef HUMANDETECTION_MESSAGE_CONNECT_SERVICE_H
#define HUMANDETECTION_MESSAGE_CONNECT_SERVICE_H

#include <ros/service_traits.h>


#include <humandetection/connect_serviceRequest.h>
#include <humandetection/connect_serviceResponse.h>


namespace humandetection
{

struct connect_service
{

typedef connect_serviceRequest Request;
typedef connect_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct connect_service
} // namespace humandetection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::humandetection::connect_service > {
  static const char* value()
  {
    return "f373a4b174400403f47052cfc240215e";
  }

  static const char* value(const ::humandetection::connect_service&) { return value(); }
};

template<>
struct DataType< ::humandetection::connect_service > {
  static const char* value()
  {
    return "humandetection/connect_service";
  }

  static const char* value(const ::humandetection::connect_service&) { return value(); }
};


// service_traits::MD5Sum< ::humandetection::connect_serviceRequest> should match 
// service_traits::MD5Sum< ::humandetection::connect_service > 
template<>
struct MD5Sum< ::humandetection::connect_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::humandetection::connect_service >::value();
  }
  static const char* value(const ::humandetection::connect_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::humandetection::connect_serviceRequest> should match 
// service_traits::DataType< ::humandetection::connect_service > 
template<>
struct DataType< ::humandetection::connect_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::humandetection::connect_service >::value();
  }
  static const char* value(const ::humandetection::connect_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::humandetection::connect_serviceResponse> should match 
// service_traits::MD5Sum< ::humandetection::connect_service > 
template<>
struct MD5Sum< ::humandetection::connect_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::humandetection::connect_service >::value();
  }
  static const char* value(const ::humandetection::connect_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::humandetection::connect_serviceResponse> should match 
// service_traits::DataType< ::humandetection::connect_service > 
template<>
struct DataType< ::humandetection::connect_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::humandetection::connect_service >::value();
  }
  static const char* value(const ::humandetection::connect_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HUMANDETECTION_MESSAGE_CONNECT_SERVICE_H
