// Generated by gencpp from file humandetection/detectionH_world_coordinates.msg
// DO NOT EDIT!


#ifndef HUMANDETECTION_MESSAGE_DETECTIONH_WORLD_COORDINATES_H
#define HUMANDETECTION_MESSAGE_DETECTIONH_WORLD_COORDINATES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace humandetection
{
template <class ContainerAllocator>
struct detectionH_world_coordinates_
{
  typedef detectionH_world_coordinates_<ContainerAllocator> Type;

  detectionH_world_coordinates_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , azimuth(0.0)  {
    }
  detectionH_world_coordinates_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , azimuth(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _azimuth_type;
  _azimuth_type azimuth;




  typedef boost::shared_ptr< ::humandetection::detectionH_world_coordinates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::humandetection::detectionH_world_coordinates_<ContainerAllocator> const> ConstPtr;

}; // struct detectionH_world_coordinates_

typedef ::humandetection::detectionH_world_coordinates_<std::allocator<void> > detectionH_world_coordinates;

typedef boost::shared_ptr< ::humandetection::detectionH_world_coordinates > detectionH_world_coordinatesPtr;
typedef boost::shared_ptr< ::humandetection::detectionH_world_coordinates const> detectionH_world_coordinatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::humandetection::detectionH_world_coordinates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::humandetection::detectionH_world_coordinates_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace humandetection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/msg', '/opt/ros/indigo/share/sensor_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/msg'], 'humandetection': ['humandetection/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::humandetection::detectionH_world_coordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::humandetection::detectionH_world_coordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::humandetection::detectionH_world_coordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::humandetection::detectionH_world_coordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::humandetection::detectionH_world_coordinates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::humandetection::detectionH_world_coordinates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::humandetection::detectionH_world_coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b3dda31fa266b1e11c637c1ee011b60";
  }

  static const char* value(const ::humandetection::detectionH_world_coordinates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b3dda31fa266b1eULL;
  static const uint64_t static_value2 = 0x11c637c1ee011b60ULL;
};

template<class ContainerAllocator>
struct DataType< ::humandetection::detectionH_world_coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "humandetection/detectionH_world_coordinates";
  }

  static const char* value(const ::humandetection::detectionH_world_coordinates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::humandetection::detectionH_world_coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# IDL struct ::detectionH::world_coordinates\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 azimuth\n\
";
  }

  static const char* value(const ::humandetection::detectionH_world_coordinates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::humandetection::detectionH_world_coordinates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.azimuth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct detectionH_world_coordinates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::humandetection::detectionH_world_coordinates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::humandetection::detectionH_world_coordinates_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "azimuth: ";
    Printer<float>::stream(s, indent + "  ", v.azimuth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMANDETECTION_MESSAGE_DETECTIONH_WORLD_COORDINATES_H
