// Generated by gencpp from file humandetection/detectionH_people.msg
// DO NOT EDIT!


#ifndef HUMANDETECTION_MESSAGE_DETECTIONH_PEOPLE_H
#define HUMANDETECTION_MESSAGE_DETECTIONH_PEOPLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <humandetection/detectionH_world_coordinates.h>

namespace humandetection
{
template <class ContainerAllocator>
struct detectionH_people_
{
  typedef detectionH_people_<ContainerAllocator> Type;

  detectionH_people_()
    : ID(0)
    , coordinates()  {
    }
  detectionH_people_(const ContainerAllocator& _alloc)
    : ID(0)
    , coordinates(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _ID_type;
  _ID_type ID;

   typedef  ::humandetection::detectionH_world_coordinates_<ContainerAllocator>  _coordinates_type;
  _coordinates_type coordinates;




  typedef boost::shared_ptr< ::humandetection::detectionH_people_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::humandetection::detectionH_people_<ContainerAllocator> const> ConstPtr;

}; // struct detectionH_people_

typedef ::humandetection::detectionH_people_<std::allocator<void> > detectionH_people;

typedef boost::shared_ptr< ::humandetection::detectionH_people > detectionH_peoplePtr;
typedef boost::shared_ptr< ::humandetection::detectionH_people const> detectionH_peopleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::humandetection::detectionH_people_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::humandetection::detectionH_people_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace humandetection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/msg', '/opt/ros/indigo/share/sensor_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/msg'], 'humandetection': ['humandetection/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::humandetection::detectionH_people_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::humandetection::detectionH_people_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::humandetection::detectionH_people_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::humandetection::detectionH_people_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::humandetection::detectionH_people_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::humandetection::detectionH_people_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::humandetection::detectionH_people_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4767d24266497e5e741d897f7c4b3c21";
  }

  static const char* value(const ::humandetection::detectionH_people_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4767d24266497e5eULL;
  static const uint64_t static_value2 = 0x741d897f7c4b3c21ULL;
};

template<class ContainerAllocator>
struct DataType< ::humandetection::detectionH_people_<ContainerAllocator> >
{
  static const char* value()
  {
    return "humandetection/detectionH_people";
  }

  static const char* value(const ::humandetection::detectionH_people_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::humandetection::detectionH_people_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# IDL struct ::detectionH::people\n\
int32 ID\n\
detectionH_world_coordinates coordinates\n\
\n\
================================================================================\n\
MSG: humandetection/detectionH_world_coordinates\n\
# IDL struct ::detectionH::world_coordinates\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 azimuth\n\
";
  }

  static const char* value(const ::humandetection::detectionH_people_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::humandetection::detectionH_people_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ID);
      stream.next(m.coordinates);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct detectionH_people_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::humandetection::detectionH_people_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::humandetection::detectionH_people_<ContainerAllocator>& v)
  {
    s << indent << "ID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ID);
    s << indent << "coordinates: ";
    s << std::endl;
    Printer< ::humandetection::detectionH_world_coordinates_<ContainerAllocator> >::stream(s, indent + "  ", v.coordinates);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMANDETECTION_MESSAGE_DETECTIONH_PEOPLE_H
