// Generated by gencpp from file humandetection/detectionH_Detections.msg
// DO NOT EDIT!


#ifndef HUMANDETECTION_MESSAGE_DETECTIONH_DETECTIONS_H
#define HUMANDETECTION_MESSAGE_DETECTIONH_DETECTIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <humandetection/detectionH_Frame.h>

namespace humandetection
{
template <class ContainerAllocator>
struct detectionH_Detections_
{
  typedef detectionH_Detections_<ContainerAllocator> Type;

  detectionH_Detections_()
    : frame()  {
    }
  detectionH_Detections_(const ContainerAllocator& _alloc)
    : frame(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::humandetection::detectionH_Frame_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::humandetection::detectionH_Frame_<ContainerAllocator> >::other >  _frame_type;
  _frame_type frame;




  typedef boost::shared_ptr< ::humandetection::detectionH_Detections_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::humandetection::detectionH_Detections_<ContainerAllocator> const> ConstPtr;

}; // struct detectionH_Detections_

typedef ::humandetection::detectionH_Detections_<std::allocator<void> > detectionH_Detections;

typedef boost::shared_ptr< ::humandetection::detectionH_Detections > detectionH_DetectionsPtr;
typedef boost::shared_ptr< ::humandetection::detectionH_Detections const> detectionH_DetectionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::humandetection::detectionH_Detections_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::humandetection::detectionH_Detections_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace humandetection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/msg', '/opt/ros/indigo/share/sensor_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/msg'], 'humandetection': ['humandetection/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::humandetection::detectionH_Detections_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::humandetection::detectionH_Detections_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::humandetection::detectionH_Detections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::humandetection::detectionH_Detections_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::humandetection::detectionH_Detections_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::humandetection::detectionH_Detections_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::humandetection::detectionH_Detections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9c5750cb5d756220fa928bf7642c8f0";
  }

  static const char* value(const ::humandetection::detectionH_Detections_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9c5750cb5d75622ULL;
  static const uint64_t static_value2 = 0x0fa928bf7642c8f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::humandetection::detectionH_Detections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "humandetection/detectionH_Detections";
  }

  static const char* value(const ::humandetection::detectionH_Detections_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::humandetection::detectionH_Detections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# IDL struct ::detectionH::Detections\n\
detectionH_Frame[] frame\n\
\n\
================================================================================\n\
MSG: humandetection/detectionH_Frame\n\
# IDL struct ::detectionH::Frame\n\
int32 frameNumber\n\
detectionH_timestamp time\n\
detectionH_people[] people\n\
\n\
================================================================================\n\
MSG: humandetection/detectionH_timestamp\n\
# IDL struct ::detectionH::timestamp\n\
uint32 sec\n\
uint32 usec\n\
\n\
================================================================================\n\
MSG: humandetection/detectionH_people\n\
# IDL struct ::detectionH::people\n\
int32 ID\n\
detectionH_world_coordinates coordinates\n\
\n\
================================================================================\n\
MSG: humandetection/detectionH_world_coordinates\n\
# IDL struct ::detectionH::world_coordinates\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 azimuth\n\
";
  }

  static const char* value(const ::humandetection::detectionH_Detections_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::humandetection::detectionH_Detections_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct detectionH_Detections_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::humandetection::detectionH_Detections_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::humandetection::detectionH_Detections_<ContainerAllocator>& v)
  {
    s << indent << "frame[]" << std::endl;
    for (size_t i = 0; i < v.frame.size(); ++i)
    {
      s << indent << "  frame[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::humandetection::detectionH_Frame_<ContainerAllocator> >::stream(s, indent + "    ", v.frame[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMANDETECTION_MESSAGE_DETECTIONH_DETECTIONS_H
